# Generated by Django 3.2 on 2021-12-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRS', '0002_auto_20211129_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='resvInfo',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
